### ISSUE TITLE
Extension manager no longer shows anything in search

### ISSUE THREAD

**Issue by Teh404Gal2** [mjakeman/extension-manager#575]
**Describe the bug**
just like the title, i tried with both warp on and off and it seems like its not an issue on gnome's backend since their site still works
Internet connection does work since i was able to access gnome's extensions website

**System Information:**
 - Distro: VanillaOS orchid
 - Extension Manager version: 0.4.3
 - Package format: Flatpak

![Capture d’écran du 2024-02-22 19-18-09](https://github.com/mjakeman/extension-manager/assets/143562763/b6497bf9-3f15-474c-82e6-2aed92d51329)
![Capture d’écran du 2024-02-22 19-20-08](https://github.com/mjakeman/extension-manager/assets/143562763/57ecd3fc-013f-46fd-af07-60d5eee5a213)

**Comment by Teh404Gal2** [comment]
Nvm this does seem like a gnome backend issue, native messaging host wont work either

**Comment by Teh404Gal2** [comment]
reopening cus it seems like this might be an issue with just this app i think

**Comment by oscfdezdz** [comment]
I had a virtual machine of VanillaOS 2 from when the beta version came out and I can't reproduce the bug, it works as expected here. I thought you might be running into #397, which was fixed after version 0.4.3, but it wouldn't make sense when the search is empty.

**Comment by mjakeman** [comment]
@Teh404Gal2 Out of curiosity, do you have a VPN/HTTP Proxy set up? Or any kind of "interesting" network config?

I remember we had an issue like this a year or so ago, but it went away when I redid the web backend.

**Comment by Teh404Gal2** [comment]
I do have warp-cli baked into the custom vanilla image im using but ive also been using that tool (with the same repo) while i was on debian 12 and extension manager did work, ima go and test it in a few minutes.

**Comment by Teh404Gal2** [comment]
I have disabled warp, and killed the app then reopened it,
it looks like its still not working and even gradience's search doesnt work, so idk how this issue exists in two apps

**Comment by Teh404Gal2** [comment]
OOPS looks like all of this was just caused by a misconfigured gnome settings proxy settings thingy
which i didnt notice because apparently only some apps respected that settings, including yours, sorry for bothering you :(
